version: '2'
services:
  robotmaster_node:
    image: "robotmaster"
    container_name: robotmaster_node
    network_mode: "host"
    environment:
      - "HOST_OS=linux"
      - "ROS_IP=192.168.27.1"
      - "ROS_MASTER_URI=http://192.168.27.1:11311"
      - "TURTLEBOT3_MODEL=waffle_pi"
    volumes:
      - /home/sw/projects/robotmaster:/root/projects/robotmaster
      - /home/sw/projects/rosbot/taskcontroller:/root/projects/taskcontroller
    ports:
      - "8000:8000"
