version: '2'
services:
  roscore_node:
    image: "ros:kinetic-robot"
    container_name: roscore_node
    environment:
      - "ROS_IP=192.168.3.104"
    network_mode: "host"
    command:
      - roscore

  robotmaster_node:
    build: .
    container_name: robotmaster_node
    network_mode: "host"
    environment:
      - "ROS_IP=192.168.3.104"
      - "ROS_MASTER_URI=http://192.168.3.104:11311"
      - "TURTLEBOT3_MODEL=waffle_pi"
    volumes:
      - /home/sw/projects:/projects
